#!/bin/bash

SELF=(`realpath $0`)
SELF_DIR=(`dirname $SELF`)
pkill -f 'localhost:9090'
xdg-open http://localhost:9090 > /dev/null 2>&1 &
echo "Starting PHP server in $SELF_DIR. Press Ctrl+C to stop."
WORK_DIR=`pwd` php -d variables_order=EGPCS -S localhost:9090 $SELF_DIR/index.php > /dev/null 2>&1
